[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'junegunn/goyo.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = """
" <Leader>f{char} to move to {char}
map  <Leader>f <Plug>(easymotion-bd-f)
nmap <Leader>f <Plug>(easymotion-overwin-f)

" Move to line
map <Leader>L <Plug>(easymotion-bd-jk)
nmap <Leader>L <Plug>(easymotion-overwin-line)

" Move to word
map  <Leader>w <Plug>(easymotion-bd-w)
nmap <Leader>w <Plug>(easymotion-overwin-w)
"""

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = """
let g:airline#extensions#tabline#enabled = 1
"""

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# tokyonight
# [[plugins]]
# repo = 'ghifarit53/tokyonight-vim'
# hook_add = """
# set termguicolors
# let g:tokyonight_enable_italic = 1
# let g:tokyonight_style = 'night'
# let g:tokyonight_style = 'storm'
# """
# hook_post_source = """
# colorscheme tokyonight
# """

# onedark
[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = """
au ColorScheme * hi LineNr       ctermbg=none ctermfg=240 cterm=italic " 行番号
au ColorScheme * hi StatusLine   ctermbg=none " アクティブなステータスライン
au ColorScheme * hi StatusLineNC ctermbg=none " 非アクティブなステータスライン
au ColorScheme * hi Comment      ctermfg=243 cterm=italic " コメントアウト
au ColorScheme * hi Statement    ctermfg=45
au ColorScheme * hi DiffAdd      ctermbg=24  " 追加行
au ColorScheme * hi Identifier   ctermfg=45 "cterm=bold
"""
hook_post_source = """
colorscheme onedark
"""

# # hybrid
# [[plugins]]
# repo = 'w0ng/vim-hybrid'
# hook_add = """
# let g:hybrid_custom_term_colors = 1
# """
# hook_post_source = """
# colorscheme hybrid
# """

# molokai
# [[plugins]]
# repo = 'tomasr/molokai'
# hook_add = """
# let g:molokai_original = 1
# let g:rehash256 = 1
# """
# hook_post_source = """
# colorscheme molokai
# """

# # night owl
# [[plugins]]
# repo = 'haishanh/night-owl.vim'
# hook_add = """
# set termguicolors
# """
# hook_post_source = """
# colorscheme night-owl
# """

[[plugins]]
repo = 'pandysong/ghost-text.vim'
