# js, ts
# [[plugins]]
# repo  = 'Quramy/tsuquyomi'
# on_ft = ['typescript', 'typescriptreact']

# [[plugins]]
# repo  = 'pangloss/vim-javascript'
# on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescriptreact']

# [[plugins]]
# repo = 'othree/yajs.vim'
# on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescriptreact']

# [[plugin]]
# repo = 'othree/es.next.syntax.vim'
# on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescriptreact']

# [[plugin]]
# repo = 'othree/javascript-libraries-syntax.vim'
# on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescriptreact']
# hook_add = '''
#   let g:used_javascript_libs = 'jquery,underscore,react,flux,jasmine,d3'
#   let b:javascript_lib_use_jquery = 1
#   let b:javascript_lib_use_underscore = 1
#   let b:javascript_lib_use_react = 1
#   let b:javascript_lib_use_flux = 1
#   let b:javascript_lib_use_jasmine = 1
#   let b:javascript_lib_use_d3 = 1
# '''

# [[plugin]]
# repo = 'yuezk/vim-js'
# on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescriptreact']

# [[plugin]]
# repo = 'maxmellon/vim-jsx-pretty'
# on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescriptreact']

[[plugin]]
repo = 'leafgarland/typescript-vim'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescriptreact']

[[plugin]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescriptreact']


# css
[[plugins]]
repo  = 'othree/html5.vim'
on_ft = ['html']

# R
[[plugins]]
repo  = 'jalvesaq/Nvim-R'
rev = 'stable'
on_ft = ['r']

# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'vue', 'javascript', 'htmldjango', 'typescriptreact']

# markdown
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

# golang
# [[plugins]]
# repo = 'fatih/vim-go'
# on_ft = ['go']

# arduino
[[plugins]]
repo = 'sudar/vim-arduino-syntax'
on_ft = ['arduino']

# vue
[[plugins]]
repo = 'posva/vim-vue'
hook_post_source = """
autocmd FileType vue syntax sync fromstart
"""
on_ft = ['vue']

# python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

# depends
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

# tex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_add = '''
  let g:vimtex_compiler_latexmk_engines = {'_': '-pdfdvi'}
  let g:tex_flavor = "tex"
  let g:vimtex_view_method= 'skim'
  " set conceallevel=2
  " let g:tex_conceal = "abdmgs"
  set conceallevel=0
  " let g:tex_conceal = ""
  " let g:vimtex_quickfix_latexlog = {'default': 0}
'''
hook_source = '''
  if empty(v:servername) && exists('*remote_startserver')
    call remote_startserver('VIM')
  endif
  set conceallevel=0
'''

# # インサートモードに入ったら読み込む
# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# on_source = ['nvim-yarp', 'vim-hug-neovim-rpc']
# hook_post_source = """
# let g:deoplete#enable_at_startup = 1
# """

# ifとかの終了宣言を自動で挿入してくれる
# [[plugins]]
# repo = 'tpope/vim-endwise'
# on_i = 1

[[plugins]]
repo   = 'Shougo/unite.vim'

# unite.vim を読み込んだら一緒に読み込む
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

# 特定のコマンドを打ったら読み込む
[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']

# [[plugins]]
# repo  = 'mechatroner/rainbow_csv'
# on_ft = ['csv']

[[plugins]]
repo  = 'chrisbra/csv.vim'
on_ft = ['csv']
