# 特定のファイルタイプで読み込む
[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = ['typescript']

# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'vue']

# markdown
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

# golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

# arduino
[[plugins]]
repo = 'sudar/vim-arduino-syntax'
on_ft = ['arduino']

# vue
[[plugins]]
repo = 'posva/vim-vue'
hook_post_source = """
autocmd FileType vue syntax sync fromstart
"""
on_ft = ['vue']

# python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

# depends
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

# インサートモードに入ったら読み込む
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_source = ['nvim-yarp', 'vim-hug-neovim-rpc']
hook_post_source = """
let g:deoplete#enable_at_startup = 1
"""

# ifとかの終了宣言を自動で挿入してくれる
[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1

[[plugins]]
repo   = 'Shougo/unite.vim'

# unite.vim を読み込んだら一緒に読み込む
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

# 特定のコマンドを打ったら読み込む
[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']

