[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'junegunn/goyo.vim'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'Shougo/vimproc.vim'
# git clone 後、実行すべきコマンド
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

# カーソル位置のコンテキストに合わせてftを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# カーソル位置のコンテキストのftを判定するライブラリ
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# テキストオブジェクトの拡張
[[plugins]]
repo = 'tpope/vim-surround'

# マイクロマクロの拡張
[[plugins]]
repo = 'tpope/vim-repeat'


# 特定の条件で読み込みたいとき
[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

# ステータスラインの表示内容強化
# [[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = """
let g:airline#extensions#tabline#enabled = 1
"""

# インデントの可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# コメント gcc, gcG
[[plugins]]
repo = 'tpope/vim-commentary'

# pairs such as {, [
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# ステータスラインのテーマ
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = """
" let g:airline_theme = 'tokyonight'
"""

# # tokyonight
# [[plugins]]
# repo = 'ghifarit53/tokyonight-vim'
# hook_add = """
# " set termguicolors
# " let g:tokyonight_enable_italic = 1
# let g:tokyonight_style = 'night'
# " let g:tokyonight_style = 'storm'
# """
# hook_post_source = """
# colorscheme tokyonight
# """

# # onedark
# [[plugins]]
# repo = 'joshdick/onedark.vim'
# hook_add = """
# au ColorScheme * hi LineNr       ctermbg=none ctermfg=240 cterm=italic " 行番号
# au ColorScheme * hi StatusLine   ctermbg=none " アクティブなステータスライン
# au ColorScheme * hi StatusLineNC ctermbg=none " 非アクティブなステータスライン
# au ColorScheme * hi Comment      ctermfg=243 cterm=italic " コメントアウト
# au ColorScheme * hi Statement    ctermfg=45
# au ColorScheme * hi DiffAdd      ctermbg=24  " 追加行
# au ColorScheme * hi Identifier   ctermfg=45 "cterm=bold
# """
# hook_post_source = """
# colorscheme onedark
# """

# # hybrid
# [[plugins]]
# repo = 'w0ng/vim-hybrid'
# hook_add = """
# let g:hybrid_custom_term_colors = 1
# """
# hook_post_source = """
# colorscheme hybrid
# ""

# molokai
[[plugins]]
repo = 'tomasr/molokai'
hook_add = """
let g:molokai_original = 1
let g:rehash256 = 1
"""
hook_post_source = """
colorscheme molokai
"""

# # night owl
# [[plugins]]
# repo = 'haishanh/night-owl.vim'
# hook_add = """
# set termguicolors
# """
# hook_post_source = """
# colorscheme night-owl
# """
