# markdown
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

# markdown
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''
on_ft = ['json']

[[plugins]]
repo = 'sebdah/vim-delve'
on_ft = ['go']
hook_add = """
let g:delve_new_command = 'new'
"""

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']
hook_add = """
let g:dart_format_on_save = 1
"""

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = ['dart']
hook_add = """
nnoremap <leader>fa :FlutterRun<cr>
nnoremap <leader>fq :FlutterQuit<cr>
nnoremap <leader>fr :FlutterHotReload<cr>
nnoremap <leader>fR :FlutterHotRestart<cr>
"""
