# markdown
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

# markdown
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''
on_ft = ['json']

[[plugins]]
repo = 'sebdah/vim-delve'
on_ft = ['go']
hook_add = """
let g:delve_new_command = 'new'
"""
[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']
