# Use custom format
format = """
[┌───────────────────>](bold green)
[│](bold green)$username$hostname$directory$rust$package
[└─>](bold green)"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[cmd_duration]
min_time = 500
format = "underwent [$duration](bold yellow)"

[gcloud]
format = ""

# packageモジュールを無効にし、プロンプトから完全に隠します
[package]
disabled = true

[character]
vicmd_symbol = "[V](bold green) "
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[directory]
truncation_length = 8
truncation_symbol = "…/"
